### ISSUE TITLE
Incorrect body sent for updateContact()

### ISSUE THREAD

**Issue by davewelsh** [icontact/icontact-pro-api-php#3]
updateContact attempts to send an array of contacts to POST "https://api.icpro.co/icp/a/{$accountId}/c/{$folderId}/contacts/${contactId}". It should be sending a single contact.

Line 606
$oContact = $this->makeCall("/a/{$this->getCompanyId()}/c/{$this->getProfileId()}/contacts/{$iContactId}", 'POST', array($aContact), 'contact');

needs to be replaced with

$oContact = $this->makeCall("/a/{$this->getCompanyId()}/c/{$this->getProfileId()}/contacts/{$iContactId}", 'POST', $aContact, 'contact');

**Comment by aikar** [comment]
Thanks for the catch!
